# docker-compose.yml
version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ovicell_db
      POSTGRES_USER: ovicell_user
      POSTGRES_PASSWORD: ovicell_password
    ports:
      - "5432:5432"
